version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: moviezone_backend
    restart: always
    network_mode: "host"
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:Vicojohns%40100@db.avekvmjzdxanwxuwvbwq.supabase.co:5432/postgres}
      - JWT_SECRET=moviezone_jwt_secret_key_12345!
      - CLIENT_URL=https://vjpulse.site
      - REELPLEXI_API_KEY=${REELPLEXI_API_KEY:-}
    volumes:
      - db_data:/app/prisma

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: moviezone_frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - moviezone_net

volumes:
  db_data:

networks:
  moviezone_net:
    driver: bridge
