export const catalogMovies = [
  // --- VJ JUNIOR ---
  {
    title: 'The Beekeeper (Luganda)',
    description: 'In The Beekeeper, one man\'s brutal campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful clandestine organization. Voiced by VJ Junior.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '1011985',
    duration: '1h 45m',
    releaseYear: 2024,
    rating: 'R',
    genres: 'Action, Thriller',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Junior',
    originCountry: 'UG',
    region: 'east-african'
  },
  {
    title: 'Interstellar (Luganda)',
    description: 'Explorers travel through a newly discovered wormhole in space to ensure humanity\'s survival. Translated with high intellect by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '157336',
    duration: '2h 49m',
    releaseYear: 2014,
    rating: 'PG-13',
    genres: 'Sci-Fi, Adventure, Drama',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Gladiator (Luganda)',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family. Masterpiece voiceover by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/ty87IL7gRy7xs2Jv0a141l7o2qA.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/jhk6D8pim3yaByu1801kMoxXFaX.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '98',
    duration: '2h 35m',
    releaseYear: 2000,
    rating: 'R',
    genres: 'Action, Drama',
    type: 'MOVIE',
    category: 'Popular on Netflix',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Oppenheimer (Luganda)',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb, narrated eloquently by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGvC271ugXn.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '872585',
    duration: '3h 00m',
    releaseYear: 2023,
    rating: 'R',
    genres: 'Drama, History, Thriller',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Dune: Part Two (Luganda)',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Voiced by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/1pdfLPoVxWGlGivJR2pOFGDwqOt.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s52SuY.jpg',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '693134',
    duration: '2h 46m',
    releaseYear: 2024,
    rating: 'PG-13',
    genres: 'Sci-Fi, Adventure',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'John Wick: Chapter 4 (Luganda)',
    description: 'John Wick uncovers a path to defeating The High Table, translated with non-stop adrenaline by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/vZloFAK7NHYSTW35Mv3zFiVJviD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/h8gWv0zCefvknEJhGUtj19RZmo4.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '603692',
    duration: '2h 49m',
    releaseYear: 2023,
    rating: 'R',
    genres: 'Action, Thriller, Crime',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Top Gun: Maverick (Luganda)',
    description: 'Maverick trains a detachment of graduates for a specialized mission. High-flying aviation action voiced by VJ Junior.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/62HCfaYToLhczccLhGfvz2zP9m0.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAivAX55mlTUtqE2.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '361743',
    duration: '2h 11m',
    releaseYear: 2022,
    rating: 'PG-13',
    genres: 'Action, Drama',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'The Dark Knight (Luganda)',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest tests. VJ Junior classic.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/nMKmy8FiJRiHKBDStwhRMNyw5st.jpg',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '155',
    duration: '2h 32m',
    releaseYear: 2008,
    rating: 'PG-13',
    genres: 'Action, Crime, Drama',
    type: 'MOVIE',
    category: 'Popular on Netflix',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  },

  // --- VJ ICE P ---
  {
    title: 'Extraction 2 (Luganda)',
    description: 'Tyler Rake returns for another deadly clandestine extraction mission, translated with intense action commentary by VJ Ice P.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '697843',
    duration: '2h 02m',
    releaseYear: 2023,
    rating: 'R',
    genres: 'Action, Thriller',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Ice P',
    originCountry: 'UG',
    region: 'east-african'
  },
  {
    title: 'Fast X (Luganda)',
    description: 'Dom Toretto and his family are targeted by the vengeful son of drug lord Hernan Reyes. Voiced with energetic speed by VJ Ice P.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/fiVW06LEDB9zFivmOLiHrzKVzG.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/4XM8DUTQb3lhKWFCWy9iAKUv8vB.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '385687',
    duration: '2h 21m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Action, Crime, Thriller',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Ice P',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Creed III (Luganda)',
    description: 'Adonis Creed faces off against his childhood friend and former boxing prodigy Damian. Intense fighting sound effects translated by VJ Ice P.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/cvsXj3G9YmYiBvvy3uP1yC8F8t.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/5i6WShwJbuFiUtxMiFY2Wp91Fv.jpg',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '677179',
    duration: '1h 56m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Action, Drama',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Ice P',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Mission: Impossible - Dead Reckoning (Luganda)',
    description: 'Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands. High adrenaline action commentary by VJ Ice P.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '575264',
    duration: '2h 43m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Action, Thriller, Adventure',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Ice P',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Ip Man 4: The Finale (Luganda)',
    description: 'Wing Chun grandmaster Ip Man travels to San Francisco where his student Bruce Lee has upset the martial arts community. Martial arts action translated by VJ Ice P.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/2L2uB7n7a1h22b10z0k4y9y5y6.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/b34j283749z.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '449924',
    duration: '1h 47m',
    releaseYear: 2019,
    rating: 'PG-13',
    genres: 'Action, Drama, Martial Arts',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Ice P',
    originCountry: 'CN',
    region: 'asian'
  },

  // --- VJ EMMY ---
  {
    title: 'Lovely Runner (Luganda)',
    description: 'Immerse yourself in this hit Korean romantic time-travel series translated with dramatic flair by VJ Emmy for Ugandan drama fans.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '223344',
    duration: '16 Episodes',
    releaseYear: 2024,
    rating: 'TV-14',
    genres: 'Romance, Comedy, Fantasy',
    type: 'SHOW',
    category: 'K-Drama Hits',
    vj: 'VJ Emmy',
    originCountry: 'KR',
    region: 'kdrama'
  },
  {
    title: 'Jawan (Luganda)',
    description: 'Shah Rukh Khan stars in this explosive Bollywood blockbuster translated with full passion and emotional commentary by VJ Emmy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1460882010656-566798143d81?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '872906',
    duration: '2h 49m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Action, Thriller, Drama',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Emmy',
    originCountry: 'IN',
    region: 'bollywood'
  },
  {
    title: 'Queen of Tears (Luganda)',
    description: 'A miraculous love story of a married couple overcoming a dizzying crisis. Phenomenal Korean drama commentary by VJ Emmy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '242875',
    duration: '16 Episodes',
    releaseYear: 2024,
    rating: 'TV-14',
    genres: 'Romance, Drama, Comedy',
    type: 'SHOW',
    category: 'K-Drama Hits',
    vj: 'VJ Emmy',
    originCountry: 'KR',
    region: 'kdrama'
  },
  {
    title: 'Pathaan (Luganda)',
    description: 'An Indian secret agent races against time to stop a mercenary group from launching a deadly biological attack. Voiced by VJ Emmy.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/m11gVOF8qL46gPyRkyvuv2mHQkF.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/94TIjp8513.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '864692',
    duration: '2h 26m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Action, Thriller',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Emmy',
    originCountry: 'IN',
    region: 'bollywood'
  },
  {
    title: 'Crash Landing on You (Luganda)',
    description: 'A South Korean heiress accidentally paraglides into North Korea and into the life of an army officer. Masterpiece romance voiced by VJ Emmy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '94796',
    duration: '16 Episodes',
    releaseYear: 2020,
    rating: 'TV-14',
    genres: 'Romance, Comedy, Drama',
    type: 'SHOW',
    category: 'K-Drama Hits',
    vj: 'VJ Emmy',
    originCountry: 'KR',
    region: 'kdrama'
  },

  // --- VJ MARK ---
  {
    title: 'Demon Slayer: Hashira Training (Luganda)',
    description: 'Tanjiro undergoes rigorous training with the Hashira. Anime action translated with energy and hype by VJ Mark.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    tmdbId: '1219601',
    duration: '8 Episodes',
    releaseYear: 2024,
    rating: 'TV-14',
    genres: 'Animation, Action, Fantasy',
    type: 'SHOW',
    category: 'Trending VJ Movies',
    vj: 'VJ Mark',
    originCountry: 'JP',
    region: 'anime'
  },
  {
    title: 'Attack on Titan: The Final Season (Luganda)',
    description: 'Eren Yeager unleashes the Rumbling upon the world. Epic anime commentary translated by VJ Mark.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/hTkJY68p88m.jpg',
    backdropUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '1429',
    duration: '28 Episodes',
    releaseYear: 2023,
    rating: 'TV-MA',
    genres: 'Animation, Action, Fantasy',
    type: 'SHOW',
    category: 'Trending VJ Movies',
    vj: 'VJ Mark',
    originCountry: 'JP',
    region: 'anime'
  },
  {
    title: 'Jujutsu Kaisen: Shibuya Arc (Luganda)',
    description: 'Sorcerers and curses clash in Shibuya in an all-out battle for survival. Voiced by VJ Mark.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '95479',
    duration: '24 Episodes',
    releaseYear: 2023,
    rating: 'TV-MA',
    genres: 'Animation, Action, Supernatural',
    type: 'SHOW',
    category: 'Trending VJ Movies',
    vj: 'VJ Mark',
    originCountry: 'JP',
    region: 'anime'
  },

  // --- VJ JINGO ---
  {
    title: 'Anulika The Queen (Nollywood)',
    description: 'Epic Nollywood royal drama translated into vibrant local commentary by VJ Jingo.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '990112',
    duration: '2h 15m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Drama, African Cinema',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Jingo',
    originCountry: 'NG',
    region: 'nollywood'
  },
  {
    title: 'The Black Book (Nollywood)',
    description: 'After his son is framed for a kidnapping, a bereaved deacon takes justice into his own hands. Voiced by VJ Jingo.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '1171821',
    duration: '2h 04m',
    releaseYear: 2023,
    rating: 'TV-MA',
    genres: 'Action, Thriller, Crime',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Jingo',
    originCountry: 'NG',
    region: 'nollywood'
  },
  {
    title: 'Jagun Jagun (Luganda)',
    description: 'A young man determined to become a powerful warrior joins an elite army and crosses paths with a ruthless warlord. Voiced by VJ Jingo.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '1154784',
    duration: '2h 14m',
    releaseYear: 2023,
    rating: 'TV-MA',
    genres: 'Action, Drama, History',
    type: 'MOVIE',
    category: 'UG VJ Exclusives',
    vj: 'VJ Jingo',
    originCountry: 'NG',
    region: 'nollywood'
  },

  // --- VJ COX ---
  {
    title: 'Godzilla x Kong: The New Empire (Luganda)',
    description: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins. Voiced with thunderous sound effects by VJ Cox.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/b0PlSFdDwbyK0cf5RxwDpaOJmTe.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/j3Z26qQy3j.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '823464',
    duration: '1h 55m',
    releaseYear: 2024,
    rating: 'PG-13',
    genres: 'Action, Sci-Fi, Adventure',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Cox',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Avatar: The Way of Water (Luganda)',
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Visual sci-fi wonder narrated by VJ Cox.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/t68W885FiHYb2yWfLz3Zqj2dEFo.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/s16H6vWoV2vMflpph8M.jpg',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '76600',
    duration: '3h 12m',
    releaseYear: 2022,
    rating: 'PG-13',
    genres: 'Sci-Fi, Action, Adventure',
    type: 'MOVIE',
    category: 'Popular on Netflix',
    vj: 'VJ Cox',
    originCountry: 'US',
    region: 'western'
  },

  // --- VJ ISMA ---
  {
    title: 'Deadpool & Wolverine (Luganda)',
    description: 'Deadpool is offered a place in the Marvel Cinematic Universe, but instead recruits a variant of Wolverine to save his universe. Hilarious comedy commentary by VJ Isma.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0j.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '533535',
    duration: '2h 08m',
    releaseYear: 2024,
    rating: 'R',
    genres: 'Action, Comedy, Sci-Fi',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Isma',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Kung Fu Panda 4 (Luganda)',
    description: 'Po must train a new warrior when he\'s chosen to become the Spiritual Leader of the Valley of Peace. Voiced with comedy flair by VJ Isma.',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8g4Djt4rDq9FqV2L.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/1XFoto.jpg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '1011985',
    duration: '1h 34m',
    releaseYear: 2024,
    rating: 'PG',
    genres: 'Animation, Comedy, Action',
    type: 'MOVIE',
    category: 'Popular on Netflix',
    vj: 'VJ Isma',
    originCountry: 'US',
    region: 'western'
  },

  // --- VJ SAMMY ---
  {
    title: 'Squid Game: Season 2 (Luganda)',
    description: 'Gi-hun returns to the deadly games to put an end to the secretive survival organization once and for all. Voiced by VJ Sammy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '93405',
    duration: '9 Episodes',
    releaseYear: 2024,
    rating: 'TV-MA',
    genres: 'Thriller, Drama, Mystery',
    type: 'SHOW',
    category: 'Trending VJ Movies',
    vj: 'VJ Sammy',
    originCountry: 'KR',
    region: 'kdrama'
  },
  {
    title: 'Money Heist: Korea (Luganda)',
    description: 'Thieves overtake the mint of a unified Korea. As hostages are trapped inside, police must stop them. Voiced by VJ Sammy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=600&fit=crop&q=80',
    tmdbId: '112836',
    duration: '12 Episodes',
    releaseYear: 2022,
    rating: 'TV-MA',
    genres: 'Action, Crime, Thriller',
    type: 'SHOW',
    category: 'K-Drama Hits',
    vj: 'VJ Sammy',
    originCountry: 'KR',
    region: 'kdrama'
  },
  {
    title: 'Rush Hour 3 (Luganda)',
    description: 'Inspector Lee and Detective Carter travel to Paris to protect a Chinese woman from Triad assassins. Hilarious action comedy commentary by VJ Isma.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '5137',
    duration: '1h 31m',
    releaseYear: 2007,
    rating: 'PG-13',
    genres: 'Action, Comedy, Crime',
    type: 'MOVIE',
    category: 'Popular on Netflix',
    vj: 'VJ Isma',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Central Intelligence (Luganda)',
    description: 'A mild-mannered accountant is lured into the world of international espionage by his former high school classmate. Voiced by VJ Isma.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    tmdbId: '302699',
    duration: '1h 47m',
    releaseYear: 2016,
    rating: 'PG-13',
    genres: 'Action, Comedy',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Isma',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Bad Boys: Ride or Die (Luganda)',
    description: 'Miami cops Mike Lowrey and Marcus Burnett fight corruption inside the department. High octane action commentary by VJ Ice P.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    tmdbId: '573435',
    duration: '1h 55m',
    releaseYear: 2024,
    rating: 'R',
    genres: 'Action, Comedy, Crime',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Ice P',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Barbie (Luganda)',
    description: 'Barbie and Ken are having the time of their lives in the colorful world of Barbie Land before traveling to the real world. Translated by VJ Emmy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tmdbId: '346698',
    duration: '1h 54m',
    releaseYear: 2023,
    rating: 'PG-13',
    genres: 'Comedy, Fantasy, Adventure',
    type: 'MOVIE',
    category: 'Trending VJ Movies',
    vj: 'VJ Emmy',
    originCountry: 'US',
    region: 'western'
  },
  {
    title: 'Free Guy (Luganda)',
    description: 'A bank teller discovers he is actually a background player in an open-world video game. Voiced by VJ Junior.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&h=300&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&h=600&fit=crop&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tmdbId: '550988',
    duration: '1h 55m',
    releaseYear: 2021,
    rating: 'PG-13',
    genres: 'Action, Comedy, Sci-Fi',
    type: 'MOVIE',
    category: 'Action & Adventure',
    vj: 'VJ Junior',
    originCountry: 'US',
    region: 'western'
  }
];

